### **Day 2: Pandas로 데이터 조작하기 문제집**

Pandas를 활용한 데이터 조작 문제집입니다. 각 문제에 대한 상세한 설명과 함께, 문제 해결에 도움이 되는 **힌트**를 참고하여 코드를 작성해 보세요.

---

#### **1. 붓꽃 데이터셋 (Iris Dataset)**

**문제 1. 데이터 불러오기 및 탐색**
* **문제 설명:** scikit-learn에서 붓꽃 데이터를 불러와 DataFrame으로 만드세요. `df.shape`와 `df.columns`를 사용하여 데이터의 크기와 열 이름을 확인하세요.
* **HINT:** `load_iris()` 함수로 데이터를 불러온 후, `pd.DataFrame()`으로 DataFrame을 만들고 `columns`에 `iris.feature_names`를 지정해 보세요.

In [4]:
from sklearn.datasets import load_iris
import pandas as pd

# 코드를 작성하세요

iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
print("데이터 크기:", df.shape)
print("열 이름:", df.columns)

# uv add scikit-learn, pandas
# 반환값은 Bunch 객체(딕셔너리처럼 키로 접근 + 속성 접근 가능)
# Bunch는 “dict처럼 쓰는데 점(.)으로도 접근 가능한 가벼운 컨테이너”
# 사이킷런이 내장 데이터셋을 돌려줄 때 자주 쓰는 타입
# 그래서 iris.data와 iris['data']가 같은 값이 될 수 있다.
# .shape는 (행 개수, 열 개수)를 담은 튜플
# .columns 는 열 이름을 담은 index

# 예상 출력: 데이터의 크기 (150, 4)와 열 이름

데이터 크기: (150, 4)
열 이름: Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [ ]:
iris.data

# 150 * 4 의 배열을 보여주고 있음. 리스트가 아니다. 배열이다.

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

**문제 2. 특정 조건으로 데이터 선택**
* **문제 설명:** 'species' 열의 값이 'setosa'인 행만 필터링하여 새로운 DataFrame을 만드세요.
* **HINT:** `df['species'] == 'setosa'`라는 불리언 조건으로 DataFrame을 필터링해 보세요.

In [ ]:
from sklearn.datasets import load_iris
import pandas as pd
iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names) 
# 150, 4 배열의 iris.data 를 데이터 프레임으로 만들고 열에 이름을 붙여줘라
df['species'] = iris.target_names[iris.target]
# species라는 컬럼을 추가하고
# iris.target_names = 길이 3짜리 문자열 배열로 인덱싱 해라
# iris.target: 길이 150짜리 정수 배열 (값은 0,1,2) 을

setosa_df = df[df['species'] == 'setosa']
print(setosa_df)
# df['species'] == 'setosa' 인것을 데이터 프레임해서 보여줘라

# 예상 출력: 'setosa' 종으로만 구성된 DataFrame

    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 5.1               3.5                1.4               0.2
1                 4.9               3.0                1.4               0.2
2                 4.7               3.2                1.3               0.2
3                 4.6               3.1                1.5               0.2
4                 5.0               3.6                1.4               0.2
5                 5.4               3.9                1.7               0.4
6                 4.6               3.4                1.4               0.3
7                 5.0               3.4                1.5               0.2
8                 4.4               2.9                1.4               0.2
9                 4.9               3.1                1.5               0.1
10                5.4               3.7                1.5               0.2
11                4.8               3.4                1.6               0.2
12                4.8               3.0                1.4               0.1
13                4.3               3.0                1.1               0.1
14                5.8               4.0                1.2               0.2
15                5.7               4.4                1.5               0.4
16                5.4               3.9                1.3               0.4
17                5.1               3.5                1.4               0.3
18                5.7               3.8                1.7               0.3
19                5.1               3.8                1.5               0.3
20                5.4               3.4                1.7               0.2
21                5.1               3.7                1.5               0.4
22                4.6               3.6                1.0               0.2
23                5.1               3.3                1.7               0.5
24                4.8               3.4                1.9               0.2
25                5.0               3.0                1.6               0.2
26                5.0               3.4                1.6               0.4
27                5.2               3.5                1.5               0.2
28                5.2               3.4                1.4               0.2
29                4.7               3.2                1.6               0.2
30                4.8               3.1                1.6               0.2
31                5.4               3.4                1.5               0.4
32                5.2               4.1                1.5               0.1
33                5.5               4.2                1.4               0.2
34                4.9               3.1                1.5               0.2
35                5.0               3.2                1.2               0.2
36                5.5               3.5                1.3               0.2
37                4.9               3.6                1.4               0.1
38                4.4               3.0                1.3               0.2
39                5.1               3.4                1.5               0.2
40                5.0               3.5                1.3               0.3
41                4.5               2.3                1.3               0.3
42                4.4               3.2                1.3               0.2
43                5.0               3.5                1.6               0.6
44                5.1               3.8                1.9               0.4
45                4.8               3.0                1.4               0.3
46                5.1               3.8                1.6               0.2
47                4.6               3.2                1.4               0.2
48                5.3               3.7                1.5               0.2
49                5.0               3.3                1.4               0.2

   species
0   setosa
1   setosa
2   setosa
3   setosa
4   setosa
5   setosa
6   setosa
7   setosa
8   setosa
9   setosa
10  setosa
11  setosa
12  setosa
13  setosa
14  setosa
15  setosa
16  setosa
17  setosa
18  setosa
19  setosa
20  setosa
21  setosa
22  setosa
23  setosa
24  setosa
25  setosa
26  setosa
27  setosa
28  setosa
29  setosa
30  setosa
31  setosa
32  setosa
33  setosa
34  setosa
35  setosa
36  setosa
37  setosa
38  setosa
39  setosa
40  setosa
41  setosa
42  setosa
43  setosa
44  setosa
45  setosa
46  setosa
47  setosa
48  setosa
49  setosa

In [10]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [ ]:
df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica
149,5.9,3.0,5.1,1.8,virginica

In [9]:
df = pd.DataFrame(iris.data)
df

       0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [ ]:
iris.target              # 쉽게 말해 붓꽃 종류의 답이 들어있다.

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

**문제 3. 그룹별 평균 계산**
* **문제 설명:** 'species' 열을 기준으로 데이터를 그룹화하고, 각 그룹의 'sepal length (cm)' 평균을 계산하세요.
* **HINT:** `df.groupby()`를 사용하여 'species'로 그룹화한 뒤, `['sepal length (cm)'].mean()`으로 평균을 구하세요.

In [ ]:
from sklearn.datasets import load_iris
import pandas as pd
iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['species'] = iris.target_names[iris.target]

avg_sepal_length = df.groupby('species')['sepal length (cm)'].mean()
print(avg_sepal_length)

# 예상 출력: 종별 sepal length의 평균

species
setosa        5.006
versicolor    5.936
virginica     6.588
Name: sepal length (cm), dtype: float64

In [19]:
group = df.groupby('species')
print(group.size())

species
setosa        50
versicolor    50
virginica     50
dtype: int64

**문제 4. 행과 열을 인덱스로 선택**
* **문제 설명:** `.loc`를 사용하여 50번째 행의 'petal length (cm)' 값을 선택하세요.
* **HINT:** `.loc`는 라벨을 기반으로 데이터를 선택합니다. `df.loc[행라벨, 열라벨]` 형태로 사용해 보세요.

In [ ]:
from sklearn.datasets import load_iris
import pandas as pd
iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['species'] = iris.target_names[iris.target]

petal_length = df.loc[49, 'petal length (cm)']
print(petal_length)

# 0부터 시작하기 때문에 49를 해야 50번째 행이 나옴
# 예상 출력: 붓꽃 데이터의 특정 값

1.4

**문제 5. 데이터 정렬**
* **문제 설명:** 'petal length (cm)' 열을 기준으로 데이터를 내림차순으로 정렬하세요.
* **HINT:** `.sort_values()` 메서드를 사용하고, `by='컬럼명'`과 `ascending=False` 옵션을 지정해 보세요.

In [ ]:
from sklearn.datasets import load_iris
import pandas as pd
iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['species'] = iris.target_names[iris.target]

# 코드를 작성하세요
# 예상 출력: 'petal length (cm)' 값이 큰 순서대로 정렬된 DataFrame

---

#### **2. 당뇨병 데이터셋 (Diabetes Dataset)**

**문제 1. 데이터 불러오기 및 통계 요약**
* **문제 설명:** scikit-learn에서 당뇨병 데이터를 불러와 DataFrame으로 만드세요. `.describe()` 메서드를 사용하여 각 열의 통계량을 요약하세요.
* **HINT:** `load_diabetes()` 함수로 데이터를 불러온 후 `pd.DataFrame()`으로 만드세요. `diabetes.feature_names`를 `columns`로 지정해야 합니다.

In [24]:
from sklearn.datasets import load_diabetes
import pandas as pd

diabetes = load_diabetes()
df = pd.DataFrame(diabetes.data, columns=diabetes.feature_names)
df['target'] = diabetes.target
print(df.describe())

# 코드를 작성하세요
# 예상 출력: 각 열의 count, mean, std 등 요약 통계

                age           sex           bmi            bp            s1  \
count  4.420000e+02  4.420000e+02  4.420000e+02  4.420000e+02  4.420000e+02
mean  -2.511817e-19  1.230790e-17 -2.245564e-16 -4.797570e-17 -1.381499e-17
std    4.761905e-02  4.761905e-02  4.761905e-02  4.761905e-02  4.761905e-02
min   -1.072256e-01 -4.464164e-02 -9.027530e-02 -1.123988e-01 -1.267807e-01
25%   -3.729927e-02 -4.464164e-02 -3.422907e-02 -3.665608e-02 -3.424784e-02
50%    5.383060e-03 -4.464164e-02 -7.283766e-03 -5.670422e-03 -4.320866e-03
75%    3.807591e-02  5.068012e-02  3.124802e-02  3.564379e-02  2.835801e-02
max    1.107267e-01  5.068012e-02  1.705552e-01  1.320436e-01  1.539137e-01

                 s2            s3            s4            s5            s6  \
count  4.420000e+02  4.420000e+02  4.420000e+02  4.420000e+02  4.420000e+02
mean   3.918434e-17 -5.777179e-18 -9.042540e-18  9.293722e-17  1.130318e-17
std    4.761905e-02  4.761905e-02  4.761905e-02  4.761905e-02  4.761905e-02
min   -1.156131e-01 -1.023071e-01 -7.639450e-02 -1.260971e-01 -1.377672e-01
25%   -3.035840e-02 -3.511716e-02 -3.949338e-02 -3.324559e-02 -3.317903e-02
50%   -3.819065e-03 -6.584468e-03 -2.592262e-03 -1.947171e-03 -1.077698e-03
75%    2.984439e-02  2.931150e-02  3.430886e-02  3.243232e-02  2.791705e-02
max    1.987880e-01  1.811791e-01  1.852344e-01  1.335973e-01  1.356118e-01

           target
count  442.000000
mean   152.133484
std     77.093005
min     25.000000
25%     87.000000
50%    140.500000
75%    211.500000
max    346.000000

**문제 2. 여러 조건으로 데이터 필터링**
* **문제 설명:** 'age'가 0.05보다 크고 'bmi'가 0.04보다 작은 행만 필터링하여 DataFrame을 만드세요.
* **HINT:** 두 개의 조건을 `&` 연산자로 연결하고, 각 조건을 괄호로 묶어주세요. (예: `df[(조건1) & (조건2)]`)

In [ ]:
from sklearn.datasets import load_diabetes
import pandas as pd
diabetes = load_diabetes()
df = pd.DataFrame(diabetes.data, columns=diabetes.feature_names)
df['target'] = diabetes.target

filtered_df = df[(df['age'] > 0.05) & (df['bmi'] < 0.04)]
print(filtered_df)

# mask 라는 표현을 씀. 불리언 식에서 True만 표현하고 False는 가린다는 표현
# 식에 우선순위를 두기 위해 () 를 사용 
# 예상 출력: 두 조건을 모두 만족하는 행들로만 구성된 DataFrame

          age       sex       bmi        bp        s1        s2        s3  \
7    0.063504  0.050680 -0.001895  0.066629  0.090620  0.108914  0.022869
17   0.070769  0.050680  0.012117  0.056301  0.034206  0.049416 -0.039719
28   0.052606 -0.044642 -0.021295 -0.074527 -0.040096 -0.037639 -0.006584
29   0.067136  0.050680 -0.006206  0.063187 -0.042848 -0.095885  0.052322
48   0.067136  0.050680 -0.041774  0.011544  0.002559  0.005889  0.041277
51   0.059871  0.050680  0.016428  0.028758 -0.041472 -0.029184 -0.028674
59   0.063504  0.050680 -0.025607  0.011544  0.064477  0.048477  0.030232
64   0.067136  0.050680 -0.025607 -0.040099 -0.063487 -0.059873 -0.002903
72   0.063504  0.050680 -0.004050 -0.012556  0.103003  0.048790  0.056003
80   0.070769 -0.044642  0.012117  0.042529  0.071357  0.053487  0.052322
96   0.056239  0.050680  0.009961  0.049415 -0.004321 -0.012274 -0.043401
117  0.059871 -0.044642 -0.021295  0.087287  0.045213  0.031567 -0.047082
121  0.063504 -0.044642  0.017506  0.021872  0.008063  0.021546 -0.036038
154  0.067136  0.050680  0.020739 -0.005670  0.020446  0.026243 -0.002903
175  0.067136 -0.044642 -0.038540 -0.026328 -0.031840 -0.026366  0.008142
192  0.056239  0.050680 -0.030996  0.008101  0.019070  0.021233  0.033914
200  0.056239 -0.044642 -0.057941 -0.007977  0.052093  0.049103  0.056003
202  0.081666  0.050680  0.001339  0.035644  0.126395  0.091065  0.019187
204  0.110727  0.050680  0.006728  0.028758 -0.027712 -0.007264 -0.047082
211  0.092564 -0.044642  0.036907  0.021872 -0.024960 -0.016658  0.000779
212  0.067136 -0.044642  0.003494  0.035644  0.049341  0.031254  0.070730
217  0.074401 -0.044642  0.031517  0.101058  0.046589  0.036890  0.015505
227  0.067136  0.050680 -0.029918  0.057437 -0.000193 -0.015719  0.074412
233  0.067136 -0.044642  0.036907 -0.050427 -0.023584 -0.034508  0.048640
235  0.067136  0.050680 -0.014828  0.058608 -0.059359 -0.034508 -0.061809
237  0.056239 -0.044642 -0.068719 -0.068778 -0.000193 -0.001001  0.044958
253  0.081666 -0.044642  0.033673  0.008101  0.052093  0.056619 -0.017629
258  0.078034  0.050680 -0.024529 -0.042406  0.006687  0.052861 -0.069172
267  0.059871 -0.044642 -0.000817 -0.084856  0.075484  0.079478  0.004460
273  0.074401  0.050680 -0.020218  0.045972  0.074108  0.032819 -0.036038
278  0.067136  0.050680 -0.036385 -0.084856 -0.007073  0.019667 -0.054446
282  0.070769 -0.044642 -0.005128 -0.005670  0.087868  0.102965  0.011824
288  0.070769  0.050680 -0.016984  0.021872  0.043837  0.056305  0.037595
291  0.074401 -0.044642  0.018584  0.063187  0.061725  0.042840  0.008142
296  0.067136 -0.044642 -0.061174 -0.040099 -0.026336 -0.024487  0.033914
303  0.074401 -0.044642  0.034751  0.094172  0.057597  0.020293  0.022869
307  0.067136  0.050680 -0.030996  0.004658  0.024574  0.035638 -0.028674
318  0.088931 -0.044642  0.006728  0.025315  0.030078  0.008707  0.063367
323  0.070769  0.050680 -0.007284  0.049415  0.060349 -0.004445 -0.054446
331  0.081666  0.050680 -0.025607 -0.036656 -0.070367 -0.046407 -0.039719
342  0.056239  0.050680  0.021817  0.056301 -0.007073  0.018101 -0.032356
345  0.081666  0.050680 -0.002973 -0.033213  0.042462  0.057871 -0.010266
371  0.052606  0.050680 -0.009439  0.049415  0.050717 -0.019163 -0.013948
388  0.052606  0.050680 -0.024529  0.056301 -0.007073 -0.005072 -0.021311
397  0.052606 -0.044642 -0.004050 -0.030907 -0.046975 -0.058307 -0.013948
399  0.059871  0.050680  0.022895  0.049415  0.016318  0.011838 -0.013948
402  0.110727  0.050680 -0.033151 -0.022885 -0.004321  0.020293 -0.061809
408  0.063504 -0.044642 -0.050396  0.107944  0.031454  0.019354 -0.017629
414  0.081666  0.050680  0.006728 -0.004534  0.109883  0.117056 -0.032356
431  0.070769  0.050680 -0.030996  0.021872 -0.037344 -0.047034  0.033914

           s4        s5        s6  target
7    0.017703 -0.035816  0.003064    63.0
17   0.034309  0.027364 -0.001078   144.0
28  -0.039493 -0.000612 -0.054925   131.0
29  -0.076395  0.059424  0.052770   283.0
48  -0.039493 -0.059471 -0.021788    75.0
51  -0.002592 -0.002398 -0.021788   225.0
59  -0.002592  0.038394  0.019633   170.0
64  -0.039493 -0.019198  0.011349    71.0
72  -0.002592  0.084492 -0.017646   202.0
80  -0.002592  0.025395 -0.005220   143.0
96   0.034309  0.060791  0.032059   150.0
117  0.071210  0.079122  0.135612   281.0
121  0.034309  0.019907  0.011349   173.0
154 -0.002592  0.008641  0.003064   197.0
175 -0.039493 -0.027129  0.003064   127.0
192 -0.039493 -0.029526 -0.059067    91.0
200 -0.021412 -0.028323  0.044485   158.0
202  0.034309  0.084492 -0.030072   196.0
204  0.034309  0.002004  0.077622   277.0
211 -0.039493 -0.022517 -0.021788    70.0
212 -0.039493 -0.000612  0.019633    73.0
217 -0.002592  0.033654  0.044485   296.0
227 -0.050564 -0.038460  0.007207   108.0
233 -0.039493 -0.025953 -0.038357    90.0
235  0.012906 -0.005142  0.048628   124.0
237 -0.037648 -0.048359 -0.001078    72.0
253  0.034309  0.034866  0.069338   150.0
258  0.080804 -0.037129  0.056912    89.0
267  0.034309  0.023371  0.027917   115.0
273  0.071210  0.106351  0.036201   241.0
278  0.034309  0.001148  0.032059   102.0
282  0.034309 -0.008943  0.027917   230.0
288 -0.002592 -0.070209 -0.017646    80.0
291 -0.002592  0.058038 -0.059067   248.0
296 -0.039493 -0.056153 -0.059067    89.0
303 -0.002592  0.073799 -0.021788   236.0
307  0.034309  0.023371  0.081764   172.0
318 -0.039493  0.009434  0.032059   109.0
323  0.108111  0.129021  0.056912   248.0
331 -0.002592 -0.041176 -0.005220   199.0
342 -0.002592 -0.023647  0.023775   178.0
345  0.034309 -0.000612 -0.001078   139.0
371  0.034309  0.119340 -0.017646   197.0
388 -0.002592  0.026717 -0.038357   110.0
397 -0.025840  0.036060  0.023775   198.0
399 -0.002592  0.039542  0.019633   232.0
402  0.071210  0.015568  0.044485   168.0
408  0.023608  0.058038  0.040343   189.0
414  0.091875  0.054720  0.007207   131.0
431 -0.039493 -0.014960 -0.001078    66.0

**문제 3. 새로운 열 생성**
* **문제 설명:** 'bmi' 열과 'bp' 열을 사용하여 'bmi_bp_ratio'라는 새로운 열을 만드세요. (bmi / bp)
* **HINT:** `df['새로운 컬럼명'] = df['기존 컬럼1'] / df['기존 컬럼2']` 형태로 새로운 열을 생성해 보세요.

In [27]:
from sklearn.datasets import load_diabetes
import pandas as pd
diabetes = load_diabetes()
df = pd.DataFrame(diabetes.data, columns=diabetes.feature_names)
df['target'] = diabetes.target

df['bmi_bp_ratio'] = df['bmi'] / df['bp']
print(df)

# 코드를 작성하세요
# 예상 출력: 'bmi_bp_ratio' 열이 추가된 DataFrame

          age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412
2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142
..        ...       ...       ...       ...       ...       ...       ...
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674
439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674
441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816

           s4        s5        s6  target  bmi_bp_ratio
0   -0.002592  0.019907 -0.017646   151.0      2.820735
1   -0.039493 -0.068332 -0.092204    75.0      1.955142
2   -0.002592  0.002861 -0.025930   141.0     -7.839136
3    0.034309  0.022688 -0.009362   206.0      0.316319
4   -0.002592 -0.031988 -0.046641   135.0     -1.663499
..        ...       ...       ...     ...           ...
437 -0.002592  0.031193  0.007207   178.0      0.329098
438  0.034309 -0.018114  0.044485   104.0      0.235155
439 -0.011080 -0.046883  0.015491   132.0     -0.919788
440  0.026560  0.044529 -0.025930   220.0     32.142522
441 -0.039493 -0.004222  0.003064    57.0      0.897033

[442 rows x 12 columns]

**문제 4. 그룹별 평균 BMI 계산**
* **문제 설명:** 'sex' 열을 기준으로 데이터를 그룹화하고, 각 그룹의 'bmi'에 대한 평균(mean)과 표준편차(std)를 한 번에 계산하세요.
* **HINT:** `df.groupby()`를 사용하여 그룹화한 뒤, `['bmi'].agg(['mean', 'std'])` 메서드를 적용해 보세요.

In [28]:
from sklearn.datasets import load_diabetes
import pandas as pd
diabetes = load_diabetes()
df = pd.DataFrame(diabetes.data, columns=diabetes.feature_names)
df['target'] = diabetes.target

avg_bmi_by_sex = df.groupby('sex')['bmi'].agg(['mean', 'std'])
print(avg_bmi_by_sex)

# 코드를 작성하세요
# 예상 출력: 성별 bmi의 평균과 표준편차

               mean       std
sex
-0.044642 -0.003936  0.049269
 0.050680  0.004468  0.045379

**문제 5. 'target' 열의 값 빈도 계산**
* **문제 설명:** 'target' 열의 고유한 값들과 그 빈도를 계산하세요.
* **HINT:** `.value_counts()` 메서드를 사용하면 Series 내의 고유한 값들의 빈도를 계산할 수 있습니다.

In [29]:
from sklearn.datasets import load_diabetes
import pandas as pd
diabetes = load_diabetes()
df = pd.DataFrame(diabetes.data, columns=diabetes.feature_names)
df['target'] = diabetes.target

target_counts = df['target'].value_counts()
print(target_counts)

# 코드를 작성하세요
# 예상 출력: target 값의 빈도 수

target
200.0    6
72.0     6
178.0    5
71.0     5
90.0     5
        ..
146.0    1
212.0    1
120.0    1
183.0    1
57.0     1
Name: count, Length: 214, dtype: int64

---

#### **3. 캘리포니아 주택 가격 데이터셋 (California Housing Dataset)**

**문제 1. 데이터 불러오기 및 통계 요약**
* **문제 설명:** scikit-learn에서 캘리포니아 주택 데이터를 불러와 DataFrame으로 만드세요. `.describe()` 메서드를 사용하여 각 열의 통계량을 요약하세요.
* **HINT:** `fetch_california_housing()` 함수로 데이터를 불러온 후 `pd.DataFrame()`으로 만드세요. `housing.feature_names`를 `columns`로 지정해야 합니다.

In [31]:
from sklearn.datasets import fetch_california_housing
import pandas as pd

housing = fetch_california_housing()
df = pd.DataFrame(housing.data, columns=housing.feature_names)
df['target'] = housing.target
print(df.describe())

# 코드를 작성하세요
# 예상 출력: 각 열의 count, mean, std 등 요약 통계

             MedInc      HouseAge      AveRooms     AveBedrms    Population  \
count  20640.000000  20640.000000  20640.000000  20640.000000  20640.000000
mean       3.870671     28.639486      5.429000      1.096675   1425.476744
std        1.899822     12.585558      2.474173      0.473911   1132.462122
min        0.499900      1.000000      0.846154      0.333333      3.000000
25%        2.563400     18.000000      4.440716      1.006079    787.000000
50%        3.534800     29.000000      5.229129      1.048780   1166.000000
75%        4.743250     37.000000      6.052381      1.099526   1725.000000
max       15.000100     52.000000    141.909091     34.066667  35682.000000

           AveOccup      Latitude     Longitude        target
count  20640.000000  20640.000000  20640.000000  20640.000000
mean       3.070655     35.631861   -119.569704      2.068558
std       10.386050      2.135952      2.003532      1.153956
min        0.692308     32.540000   -124.350000      0.149990
25%        2.429741     33.930000   -121.800000      1.196000
50%        2.818116     34.260000   -118.490000      1.797000
75%        3.282261     37.710000   -118.010000      2.647250
max     1243.333333     41.950000   -114.310000      5.000010

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   MedInc      20640 non-null  float64
 1   HouseAge    20640 non-null  float64
 2   AveRooms    20640 non-null  float64
 3   AveBedrms   20640 non-null  float64
 4   Population  20640 non-null  float64
 5   AveOccup    20640 non-null  float64
 6   Latitude    20640 non-null  float64
 7   Longitude   20640 non-null  float64
 8   target      20640 non-null  float64
dtypes: float64(9)
memory usage: 1.4 MB

**문제 2. 특정 조건으로 데이터 선택**
* **문제 설명:** 'median_income'이 8.0보다 큰 행만 필터링하여 DataFrame을 만드세요.
* **HINT:** `df['median_income'] > 8.0`이라는 불리언 조건으로 DataFrame을 필터링해 보세요.

In [33]:
from sklearn.datasets import fetch_california_housing
import pandas as pd
housing = fetch_california_housing()
df = pd.DataFrame(housing.data, columns=housing.feature_names)
df['target'] = housing.target

filtered_df = df[df['MedInc'] > 8.0]
print(filtered_df)

# 코드를 작성하세요
# 예상 출력: 'median_income'이 8.0보다 큰 행들로만 구성된 DataFrame

        MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0       8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88
1       8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86
131    11.6017      18.0  8.335052   1.082474       533.0  2.747423     37.84
134     8.2049      28.0  6.978947   0.968421       463.0  2.436842     37.83
135     8.4010      26.0  7.530806   1.056872       542.0  2.568720     37.83
...        ...       ...       ...        ...         ...       ...       ...
20426  10.0472      11.0  9.890756   1.159664       415.0  3.487395     34.18
20427   8.6499       4.0  7.236059   1.032528      5495.0  2.553439     34.19
20428   8.7288       6.0  8.715842   1.102970      3385.0  3.351485     34.23
20436  12.5420      10.0  9.873315   1.102426      1179.0  3.177898     34.21
20503   8.2787      27.0  6.935065   1.103896       243.0  3.155844     34.33

       Longitude   target
0        -122.23  4.52600
1        -122.22  3.58500
131      -122.19  3.92600
134      -122.19  3.35200
135      -122.20  3.51200
...          ...      ...
20426    -118.69  5.00001
20427    -118.80  5.00001
20428    -118.83  4.25800
20436    -118.69  5.00001
20503    -118.75  3.30000

[690 rows x 9 columns]

**문제 3. 새로운 열 생성**
* **문제 설명:** 'households' 열과 'population' 열을 사용하여 'population_per_household'라는 새로운 열을 만드세요. (population / households)
* **HINT:** `df['새로운 컬럼명'] = df['기존 컬럼1'] / df['기존 컬럼2']` 형태로 새로운 열을 생성해 보세요.

In [ ]:
from sklearn.datasets import fetch_california_housing
import pandas as pd
housing = fetch_california_housing()
df = pd.DataFrame(housing.data, columns=housing.feature_names)
df['target'] = housing.target

print(df)

# 코드를 작성하세요
# 예상 출력: 'population_per_household' 열이 추가된 DataFrame

KeyError: 'bmi'

**문제 4. 'ocean_proximity' 열의 값 빈도 계산**
* **문제 설명:** 'ocean_proximity' 열의 고유한 값들과 그 빈도를 계산하세요.
* **HINT:** `.value_counts()` 메서드를 사용하면 Series 내의 고유한 값들의 빈도를 계산할 수 있습니다.

In [6]:
import pandas as pd
data = {
    'ocean_proximity': ['NEAR BAY', '<1H OCEAN', 'NEAR BAY', 'INLAND', '<1H OCEAN'],
    'median_income': [3.87, 4.21, 5.01, 2.50, 6.15]
}
df = pd.DataFrame(data)

ocean_proximity_counts = df['ocean_proximity'].value_counts()
print(ocean_proximity_counts)

# 코드를 작성하세요
# 예상 출력: ocean_proximity 값의 빈도 수

ocean_proximity
NEAR BAY     2
<1H OCEAN    2
INLAND       1
Name: count, dtype: int64

**문제 5. 데이터 정렬**
* **문제 설명:** 'median_house_value' 열을 기준으로 데이터를 오름차순으로 정렬하세요.
* **HINT:** `.sort_values()` 메서드를 사용하고 `by='컬럼명'`을 지정해 보세요. `ascending=True`가 기본값이므로 생략할 수 있습니다.

In [9]:
from sklearn.datasets import fetch_california_housing
import pandas as pd
housing = fetch_california_housing()
df = pd.DataFrame(housing.data, columns=housing.feature_names)
df['target'] = housing.target
df.rename(columns={'target': 'median_house_value'}, inplace=True)

sorted_df = df.sort_values(by = 'median_house_value', ascending = False)
print(sorted_df)

# 코드를 작성하세요
# 예상 출력: 'median_house_value' 값이 작은 순서대로 정렬된 DataFrame

        MedInc  HouseAge   AveRooms  AveBedrms  Population  AveOccup  \
5253   13.2935      27.0   7.607143   1.012673      2336.0  2.691244
5254   10.7937      29.0   7.471787   1.217868      1500.0  2.351097
5255    8.5153      40.0   6.407266   0.925430      1564.0  2.990440
5256   12.8665      37.0   7.457565   1.012915      1318.0  2.431734
5257   15.0001      42.0   9.229032   1.161290       829.0  2.674194
...        ...       ...        ...        ...         ...       ...
5887    2.3667      39.0   3.572464   1.217391       259.0  1.876812
9188    4.1932      52.0   3.568889   1.186667       628.0  2.791111
19802   0.5360      36.0  12.250000   3.500000        18.0  2.250000
2799    2.1000      19.0   3.774390   1.457317       490.0  2.987805
2521    1.6607      16.0   6.710526   1.921053        85.0  2.236842

       Latitude  Longitude  median_house_value
5253      34.11    -118.49             5.00001
5254      34.07    -118.48             5.00001
5255      34.07    -118.48             5.00001
5256      34.07    -118.48             5.00001
5257      34.06    -118.49             5.00001
...         ...        ...                 ...
5887      34.15    -118.33             0.17500
9188      34.24    -117.86             0.14999
19802     40.31    -123.17             0.14999
2799      36.40    -117.02             0.14999
2521      39.71    -122.74             0.14999

[20640 rows x 9 columns]